<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="4" failures="0" skipped="0" tests="4" time="1.170" timestamp="2025-04-23T20:26:36.525620" hostname="laptop-2"><testcase classname="" name="tests.test_main" time="0.000"><error message="collection failure">.venv\Lib\site-packages\_pytest\runner.py:341: in from_call
    result: Optional[TResult] = func()
.venv\Lib\site-packages\_pytest\runner.py:372: in &lt;lambda&gt;
    call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
.venv\Lib\site-packages\_pytest\python.py:531: in collect
    self._inject_setup_module_fixture()
.venv\Lib\site-packages\_pytest\python.py:545: in _inject_setup_module_fixture
    self.obj, ("setUpModule", "setup_module")
.venv\Lib\site-packages\_pytest\python.py:310: in obj
    self._obj = obj = self._getobj()
.venv\Lib\site-packages\_pytest\python.py:528: in _getobj
    return self._importtestmodule()
.venv\Lib\site-packages\_pytest\python.py:617: in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
.venv\Lib\site-packages\_pytest\pathlib.py:567: in import_path
    importlib.import_module(module_name)
..\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
&lt;frozen importlib._bootstrap&gt;:1204: in _gcd_import
    ???
&lt;frozen importlib._bootstrap&gt;:1176: in _find_and_load
    ???
&lt;frozen importlib._bootstrap&gt;:1147: in _find_and_load_unlocked
    ???
&lt;frozen importlib._bootstrap&gt;:690: in _load_unlocked
    ???
.venv\Lib\site-packages\_pytest\assertion\rewrite.py:186: in exec_module
    exec(co, module.__dict__)
tests\test_main.py:4: in &lt;module&gt;
    client = TestClient(transport=app)
E   TypeError: TestClient.__init__() got an unexpected keyword argument 'transport'</error></testcase><testcase classname="" name="tests.acid.test_database" time="0.000"><error message="collection failure">.venv\Lib\site-packages\_pytest\runner.py:341: in from_call
    result: Optional[TResult] = func()
.venv\Lib\site-packages\_pytest\runner.py:372: in &lt;lambda&gt;
    call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
.venv\Lib\site-packages\_pytest\python.py:531: in collect
    self._inject_setup_module_fixture()
.venv\Lib\site-packages\_pytest\python.py:545: in _inject_setup_module_fixture
    self.obj, ("setUpModule", "setup_module")
.venv\Lib\site-packages\_pytest\python.py:310: in obj
    self._obj = obj = self._getobj()
.venv\Lib\site-packages\_pytest\python.py:528: in _getobj
    return self._importtestmodule()
.venv\Lib\site-packages\_pytest\python.py:617: in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
.venv\Lib\site-packages\_pytest\pathlib.py:567: in import_path
    importlib.import_module(module_name)
..\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
&lt;frozen importlib._bootstrap&gt;:1204: in _gcd_import
    ???
&lt;frozen importlib._bootstrap&gt;:1176: in _find_and_load
    ???
&lt;frozen importlib._bootstrap&gt;:1147: in _find_and_load_unlocked
    ???
&lt;frozen importlib._bootstrap&gt;:690: in _load_unlocked
    ???
.venv\Lib\site-packages\_pytest\assertion\rewrite.py:186: in exec_module
    exec(co, module.__dict__)
tests\acid\test_database.py:8: in &lt;module&gt;
    client = TestClient(transport=app)
E   TypeError: TestClient.__init__() got an unexpected keyword argument 'transport'</error></testcase><testcase classname="" name="tests.security.test_security" time="0.000"><error message="collection failure">.venv\Lib\site-packages\_pytest\runner.py:341: in from_call
    result: Optional[TResult] = func()
.venv\Lib\site-packages\_pytest\runner.py:372: in &lt;lambda&gt;
    call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
.venv\Lib\site-packages\_pytest\python.py:531: in collect
    self._inject_setup_module_fixture()
.venv\Lib\site-packages\_pytest\python.py:545: in _inject_setup_module_fixture
    self.obj, ("setUpModule", "setup_module")
.venv\Lib\site-packages\_pytest\python.py:310: in obj
    self._obj = obj = self._getobj()
.venv\Lib\site-packages\_pytest\python.py:528: in _getobj
    return self._importtestmodule()
.venv\Lib\site-packages\_pytest\python.py:617: in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
.venv\Lib\site-packages\_pytest\pathlib.py:567: in import_path
    importlib.import_module(module_name)
..\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
&lt;frozen importlib._bootstrap&gt;:1204: in _gcd_import
    ???
&lt;frozen importlib._bootstrap&gt;:1176: in _find_and_load
    ???
&lt;frozen importlib._bootstrap&gt;:1147: in _find_and_load_unlocked
    ???
&lt;frozen importlib._bootstrap&gt;:690: in _load_unlocked
    ???
.venv\Lib\site-packages\_pytest\assertion\rewrite.py:186: in exec_module
    exec(co, module.__dict__)
tests\security\test_security.py:8: in &lt;module&gt;
    client = TestClient(app)
.venv\Lib\site-packages\starlette\testclient.py:429: in __init__
    super().__init__(
E   TypeError: Client.__init__() got an unexpected keyword argument 'app'</error></testcase><testcase classname="" name="tests.smoke.test_basic" time="0.000"><error message="collection failure">.venv\Lib\site-packages\_pytest\runner.py:341: in from_call
    result: Optional[TResult] = func()
.venv\Lib\site-packages\_pytest\runner.py:372: in &lt;lambda&gt;
    call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
.venv\Lib\site-packages\_pytest\python.py:531: in collect
    self._inject_setup_module_fixture()
.venv\Lib\site-packages\_pytest\python.py:545: in _inject_setup_module_fixture
    self.obj, ("setUpModule", "setup_module")
.venv\Lib\site-packages\_pytest\python.py:310: in obj
    self._obj = obj = self._getobj()
.venv\Lib\site-packages\_pytest\python.py:528: in _getobj
    return self._importtestmodule()
.venv\Lib\site-packages\_pytest\python.py:617: in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
.venv\Lib\site-packages\_pytest\pathlib.py:567: in import_path
    importlib.import_module(module_name)
..\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
&lt;frozen importlib._bootstrap&gt;:1204: in _gcd_import
    ???
&lt;frozen importlib._bootstrap&gt;:1176: in _find_and_load
    ???
&lt;frozen importlib._bootstrap&gt;:1147: in _find_and_load_unlocked
    ???
&lt;frozen importlib._bootstrap&gt;:690: in _load_unlocked
    ???
.venv\Lib\site-packages\_pytest\assertion\rewrite.py:186: in exec_module
    exec(co, module.__dict__)
tests\smoke\test_basic.py:5: in &lt;module&gt;
    client = TestClient(transport=app)
E   TypeError: TestClient.__init__() got an unexpected keyword argument 'transport'</error></testcase></testsuite></testsuites>